# -*- coding: utf-8 -*-
"""DAV MLR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaKuaCQNPMcRsZg_A_nsiGSs9Lhkg_eL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# --- 1. Generate Sample Data ---
np.random.seed(42)
X = 2 * np.random.rand(100, 3) # 100 samples, 3 features
y = 4 + 3 * X[:, 0] + 2 * X[:, 1] + 1.5 * X[:, 2] + np.random.randn(100) # Linear relationship + noise

# Convert to DataFrame for easier handling (optional but good practice)
df = pd.DataFrame(X, columns=['Feature_1', 'Feature_2', 'Feature_3'])
df['Target'] = y

print("Generated Data Head:")
display(df.head())

# --- 2. Prepare Data for Model ---
X = df[['Feature_1', 'Feature_2', 'Feature_3']]
y = df['Target']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\nShape of Training Data (X_train, y_train):", X_train.shape, y_train.shape)
print("Shape of Test Data (X_test, y_test):", X_test.shape, y_test.shape)

# --- 3. Perform Multiple Linear Regression ---
model = LinearRegression()
model.fit(X_train, y_train)

print("\nModel Coefficients:", model.coef_)
print("Model Intercept:", model.intercept_)

# --- 4. Make Predictions and Evaluate Model ---
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

# --- 5. Visualize Results ---

# Set style for plots
sns.set_style("whitegrid")

plt.figure(figsize=(14, 6))

# Plot 1: Actual vs. Predicted Values
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.scatter(y_test, y_pred, alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Perfect prediction line
plt.xlabel("Actual Target Values")
plt.ylabel("Predicted Target Values")
plt.title("Actual vs. Predicted Values")
plt.text(0.05, 0.95, f'R2 = {r2:.2f}', transform=plt.gca().transAxes, fontsize=12, verticalalignment='top')

# Plot 2: Residuals Plot
residuals = y_test - y_pred
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.scatter(y_pred, residuals, alpha=0.7)
plt.hlines(y=0, xmin=y_pred.min(), xmax=y_pred.max(), colors='r', linestyles='--')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residuals Plot")

plt.tight_layout()
plt.show()

print("\nVisualization complete. The 'Actual vs. Predicted Values' plot shows how close our predictions are to the true values, ideally clustering around the red dashed line. The 'Residuals Plot' helps us check for patterns in the errors (residuals). A good model should have residuals randomly scattered around zero.")