# -*- coding: utf-8 -*-
"""DAV PYTHON LIB .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qS0i-cuYF4Whw7s1UmW261JpMrH8hFis
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# --- Create Sample Data ---
np.random.seed(42)
data = {
    'X': np.random.rand(50) * 10,
    'Y': np.random.rand(50) * 10 + np.random.rand(50) * 2,
    'Category': np.random.choice(['A', 'B', 'C'], 50)
}
df = pd.DataFrame(data)

# For bar plot
category_counts = df['Category'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']

# --- Visualization 1: Scatter Plot using Matplotlib ---
plt.figure(figsize=(10, 6))
plt.scatter(df['X'], df['Y'], c=df['X'], cmap='viridis', s=100, alpha=0.7)
plt.title('Matplotlib Scatter Plot: X vs Y')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.colorbar(label='X Value')
plt.grid(True)
plt.show()

# --- Visualization 2: Bar Plot using Seaborn ---
plt.figure(figsize=(8, 5))
sns.barplot(x='Category', y='Count', data=category_counts, hue='Category', palette='magma', legend=False)
plt.title('Seaborn Bar Plot: Distribution of Categories')
plt.xlabel('Category')
plt.ylabel('Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()