# -*- coding: utf-8 -*-
"""DAV SLR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsPJUZejznbXgcbxT22NEY4V6GluBoAw
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 1. Generate sample data
np.random.seed(0) # for reproducibility
X = 2 * np.random.rand(100, 1) # 100 data points, 1 feature
y = 4 + 3 * X + np.random.randn(100, 1) # y = 4 + 3X + noise

print("Sample Data Generated:")
print(f"X shape: {X.shape}, y shape: {y.shape}")

# 2. Create and train the Linear Regression model
model = LinearRegression()
model.fit(X, y)

# 3. Make predictions
y_pred = model.predict(X)

# 4. Visualize the results
plt.figure(figsize=(10, 6))
plt.scatter(X, y, color='blue', label='Actual Data Points')
plt.plot(X, y_pred, color='red', linewidth=3, label='Regression Line')
plt.title('Simple Linear Regression: Actual vs. Predicted Values')
plt.xlabel('X (Feature)')
plt.ylabel('y (Target)')
plt.legend()
plt.grid(True)
plt.show()

# Print the model coefficients
print("\nLinear Regression Model Parameters:")
print(f"Intercept: {model.intercept_[0]:.2f}")
print(f"Coefficient (slope): {model.coef_[0][0]:.2f}")