# -*- coding: utf-8 -*-
"""DAV SPAM FILTERING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIJt1C4sRahk4PZp3FRSmNN1-A_1xIkE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

# Download necessary NLTK data
# Run these lines if you haven't downloaded them before
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')
try:
    PorterStemmer()
except LookupError:
    nltk.download('punkt')

# 1. Create a sample dataset
print("1. Creating sample dataset...")
data = {
    'label': ['ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham'],
    'message': [
        'Hey, how are you doing today?',
        'WINNER! You have won a free iPhone. Claim now!',
        'Can we meet tomorrow at 10 AM?',
        'Urgent! Your account has been suspended. Click here to reactivate.',
        'Remember to pick up groceries.',
        "Congratulations! You've been selected for a prize. Text WIN to 888 for details.",
        'Let\'s grab coffee soon.',
        'The weather is nice today.',
        'Limited time offer! Get 50% off on all products. Visit link.',
        "Don't forget the presentation."
    ]
}
df = pd.DataFrame(data)

print("Dataset created. First 5 rows:")
display(df.head())
print(f"Dataset shape: {df.shape}")
print(f"Label distribution:\n{df['label'].value_counts()}")

# 2. Preprocessing
print("\n2. Preprocessing data...")
# Fix: Changed 'PorterStemter' to 'PorterStemmer'
stemmer = PorterStemmer()
stopwords_english = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower() # Convert to lowercase
    text = re.sub(r'[^a-z0-9]', ' ', text) # Remove punctuation and numbers
    words = text.split() # Split into words
    words = [word for word in words if word not in stopwords_english] # Remove stop words
    words = [stemmer.stem(word) for word in words] # Stemming
    return ' '.join(words)

df['preprocessed_message'] = df['message'].apply(preprocess_text)

# Convert labels to numerical format (0 for ham, 1 for spam)
df['label_encoded'] = df['label'].map({'ham': 0, 'spam': 1})

print("Preprocessing complete. First 5 preprocessed messages:")
display(df[['message', 'preprocessed_message']].head())

# 3. Vectorization (TF-IDF)
print("\n3. Vectorizing text data...")
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Limit features to top 5000
X = tfidf_vectorizer.fit_transform(df['preprocessed_message'])
y = df['label_encoded']

print(f"TF-IDF vectorization complete. Shape of X: {X.shape}")

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
print(f"Data split into training ({X_train.shape[0]} samples) and testing ({X_test.shape[0]} samples).")

# 4. Model Training (Multinomial Naive Bayes)
print("\n4. Training Multinomial Naive Bayes model...")
model = MultinomialNB()
model.fit(X_train, y_train)
print("Model training complete.")

# 5. Evaluation
print("\n5. Evaluating model performance...")
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# 6. Visualization
print("\n6. Visualizing results (Confusion Matrix)...")
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Ham (0)', 'Spam (1)'],
            yticklabels=['Ham (0)', 'Spam (1)'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for Spam Filtering (Sample Data)')
plt.show()

print("\nSpam filtering process complete!")