# -*- coding: utf-8 -*-
"""DAV SENTIMENT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExaaaDhVyaabU63f_CGWNfb5APRK-CAi
"""

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import matplotlib.pyplot as plt
import seaborn as sns

# Download VADER lexicon (only needs to be run once)
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError:
    nltk.download('vader_lexicon')

# 1. Create a sample dataset
data = {
    'text': [
        'I love this product! It\'s amazing.',
        'This is the worst experience ever.',
        'It\'s okay, nothing special.',
        'Great service and fast delivery.',
        'I am very disappointed with the quality.',
        'Highly recommend this, very satisfied!',
        'Could be better, but not terrible.',
        'Absolutely fantastic, exceeded expectations.',
        'Total waste of money, utterly useless.',
        'Neutral feelings about this one.'
    ]
}
df = pd.DataFrame(data)

print("Sample Data:\n")
display(df.head())

# 2. Initialize the VADER sentiment intensity analyzer
sid = SentimentIntensityAnalyzer()

# Function to get sentiment scores
def get_sentiment_scores(text):
    return sid.polarity_scores(text)

# Apply sentiment analysis to the text column
df['sentiment_scores'] = df['text'].apply(get_sentiment_scores)

# Extract compound score and categorize sentiment
df['compound'] = df['sentiment_scores'].apply(lambda score_dict: score_dict['compound'])

def categorize_sentiment(compound_score):
    if compound_score >= 0.05:
        return 'Positive'
    elif compound_score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

df['sentiment'] = df['compound'].apply(categorize_sentiment)

print("\nData with Sentiment Scores:\n")
display(df)

# 3. Visualize the sentiment results

# Count plot for categorized sentiment
plt.figure(figsize=(8, 6))
sns.countplot(x='sentiment', data=df, palette='viridis', order=['Positive', 'Neutral', 'Negative'])
plt.title('Distribution of Sentiment Categories')
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Histogram of compound sentiment scores
plt.figure(figsize=(10, 6))
sns.histplot(df['compound'], bins=10, kde=True, color='skyblue')
plt.title('Distribution of Compound Sentiment Scores')
plt.xlabel('Compound Sentiment Score')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("\nSentiment analysis and visualization complete!")