# -*- coding: utf-8 -*-
"""DAV TSA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEr21EMYh4Jp-m84JqBtSouOScYM9qNb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Create a Sample Time Series Dataset ---

# Set a random seed for reproducibility
np.random.seed(42)

# Define the date range
dates = pd.date_range(start='2023-01-01', periods=100, freq='D')

# Generate some synthetic time series data
# A base trend, some seasonality, and random noise
trend = np.linspace(0, 20, 100)
seasonality = 5 * np.sin(np.linspace(0, 3 * np.pi, 100))
noise = np.random.normal(0, 2, 100)
data = trend + seasonality + noise

# Create a Pandas DataFrame
df = pd.DataFrame({'Date': dates, 'Value': data})

# Set 'Date' as the index for time series operations
df = df.set_index('Date')

print("Sample Time Series Data Head:")
display(df.head())
print("\nSample Time Series Data Info:")
df.info()

# --- 2. Perform Basic Time Series Analysis ---

# Calculate a rolling mean (e.g., 7-day moving average)
df['Rolling_Mean_7D'] = df['Value'].rolling(window=7).mean()

# Calculate a rolling standard deviation (e.g., 7-day moving standard deviation)
df['Rolling_Std_7D'] = df['Value'].rolling(window=7).std()

# Resample data to weekly frequency, taking the sum
df_weekly = df['Value'].resample('W').sum().to_frame()
df_weekly.rename(columns={'Value': 'Weekly_Sum'}, inplace=True)

print("\nData with Rolling Metrics Head:")
display(df.head(10))
print("\nWeekly Resampled Data Head:")
display(df_weekly.head())

# --- 3. Visualize the Time Series Data ---

plt.figure(figsize=(15, 8))
sns.set_style("whitegrid")

# Plot the original time series
sns.lineplot(data=df, x=df.index, y='Value', label='Original Data', color='skyblue')

# Plot the 7-day rolling mean
sns.lineplot(data=df, x=df.index, y='Rolling_Mean_7D', label='7-Day Rolling Mean', color='orange', linestyle='--')

# Plot the 7-day rolling standard deviation (optional, can be plotted as a shaded area or separate line)
# For simplicity, we'll just show the mean, but std can be added.
# plt.fill_between(df.index, df['Rolling_Mean_7D'] - df['Rolling_Std_7D'],
#                  df['Rolling_Mean_7D'] + df['Rolling_Std_7D'], color='orange', alpha=0.2, label='7-Day Rolling Std Dev')

plt.title('Time Series Data with 7-Day Rolling Mean', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Value', fontsize=12)
plt.legend(fontsize=10)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 6))
sns.barplot(x=df_weekly.index.strftime('%Y-%m-%d'), y='Weekly_Sum', data=df_weekly, color='lightgreen')
plt.title('Weekly Sum of Values', fontsize=16)
plt.xlabel('Week', fontsize=12)
plt.ylabel('Weekly Sum', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()