# -*- coding: utf-8 -*-
"""DAV ARIMA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwW7lBxDtA6g-mHq_Zk0U-T9Rhj1lleP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
from math import sqrt

# 1. Generate Sample Time Series Data
np.random.seed(42)
n_points = 100
dates = pd.date_range(start='2023-01-01', periods=n_points, freq='D')
data = np.random.normal(loc=50, scale=10, size=n_points) + np.arange(n_points) * 0.5 + np.sin(np.arange(n_points) * 0.5)

ts_data = pd.Series(data, index=dates)

print("Sample Time Series Data Head:")
print(ts_data.head())
print("\nSample Time Series Data Tail:")
print(ts_data.tail())

# 2. Split Data into Training and Testing Sets
train_size = int(len(ts_data) * 0.8)
train_data, test_data = ts_data[0:train_size], ts_data[train_size:]

print(f"\nTraining data size: {len(train_data)}")
print(f"Testing data size: {len(test_data)}")

# 3. Fit ARIMA Model
# ARIMA(p,d,q) parameters
# p: number of autoregressive terms (AR)
# d: number of non-seasonal differences (I - integrated)
# q: number of moving average terms (MA)
# For simplicity, we'll start with (5,1,0), but this should typically be determined by ACF/PACF plots.

order = (5, 1, 0) # Example order, can be tuned
model = ARIMA(train_data, order=order)
model_fit = model.fit()

print("\nARIMA Model Summary:")
print(model_fit.summary())

# 4. Make Predictions
# Get predictions for the entire dataset (in-sample + out-of-sample)
# This helps to visualize the fit on training data and forecast on test data.

# For in-sample predictions (fitted values on training data)
start_index_train = 0
end_index_train = len(train_data) - 1
predictions_train = model_fit.predict(start=start_index_train, end=end_index_train)

# For out-of-sample predictions (forecasts on test data)
start_index_test = len(train_data)
end_index_test = len(ts_data) - 1
predictions_test = model_fit.predict(start=start_index_test, end=end_index_test)

# Combine all predictions for plotting
predictions_full = pd.concat([predictions_train, predictions_test])

# 5. Evaluate the Model (on test data)
rmse = sqrt(mean_squared_error(test_data, predictions_test))
print(f"\nRMSE on Test Data: {rmse:.3f}")

# 6. Visualize the Results
plt.figure(figsize=(15, 7))
plt.plot(ts_data.index, ts_data, label='Original Data', color='blue')
plt.plot(train_data.index, train_data, label='Training Data', color='green', linestyle='--') # Emphasize training portion
plt.plot(test_data.index, test_data, label='Actual Test Data', color='red', linestyle='--') # Emphasize testing portion
plt.plot(predictions_full.index, predictions_full, label=f'ARIMA{order} Predictions', color='orange', linestyle='-')

# Plotting predictions_train separately to show the 'fitted' part more clearly
plt.plot(predictions_train.index, predictions_train, label=f'ARIMA{order} Fitted (Train)', color='purple', linestyle=':')

plt.title('ARIMA Model on Sample Time Series Data')
plt.xlabel('Date')
plt.ylabel('Value')
plt.legend()
plt.grid(True)
plt.show()