# -*- coding: utf-8 -*-
"""DAV R LANGUAGE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cz6j9yZLPmYbcgt51kI9BVLHg_x5hAC9

1. Install and load required package
install.packages("ggplot2")   # run once
library(ggplot2)
2. Sample dataset
We’ll use a built-in dataset called mtcars:
data(mtcars)
head(mtcars)
3. Scatter Plot (basic relationship)
Example: Miles per gallon vs Horsepower
ggplot(mtcars, aes(x = hp, y = mpg)) +
  geom_point(color = "blue", size = 3) +
  labs(title = "MPG vs Horsepower",
       x = "Horsepower",
       y = "Miles Per Gallon") +
  theme_minimal()
4. Bar Plot (average MPG by number of cylinders)
ggplot(mtcars, aes(x = factor(cyl), y = mpg)) +
  geom_bar(stat = "summary", fun = "mean", fill = "orange") +
  labs(title = "Average MPG by Cylinders",
       x = "Cylinders",
       y = "Average MPG") +
  theme_minimal()
5. Histogram (distribution of MPG)
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(fill = "green", bins = 10, color = "black") +
  labs(title = "Distribution of MPG",
       x = "MPG",
       y = "Count") +
  theme_minimal()
6. Boxplot (MPG by cylinders)
ggplot(mtcars, aes(x = factor(cyl), y = mpg)) +
  geom_boxplot(fill = "skyblue") +
  labs(title = "MPG Distribution by Cylinders",
       x = "Cylinders",
       y = "MPG") +
  theme_minimal()
7. Line Chart (example using sample data)
df <- data.frame(
  year = 2015:2020,
  sales = c(200, 250, 300, 280, 350, 400)
)

ggplot(df, aes(x = year, y = sales)) +
  geom_line(color = "red", size = 1) +
  geom_point(size = 3) +
  labs(title = "Sales Over Time",
       x = "Year",
       y = "Sales") +
  theme_minimal()
"""